services:
  frontend:
    build:
      context: ./WEB-IS2
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./WEB-IS2/:/app
      - node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm install --legacy-peer-deps && npm run dev -- --host 0.0.0.0"

volumes:
  node_modules: